import "./App.css";

async function getAutocompleteResults(query: string): Promise<string[]> {
  const fruits = [
    "Abiu",
    "Acaí",
    "Acerola",
    "Akebi",
    "Ackee",
    "African Cherry Orange",
    "American Mayapple",
    "Apple",
    "Apricot",
    "Araza",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Buddha's hand",
    "Cactus pear",
    "Canistelt",
    "Cempedak",
    "Cherimoya",
    "Cherry",
    "Chico fruit",
    "Cloudberry",
    "Coco de mer",
    "Coconut",
    "Crab apple",
    "Cranberry",
    "Currant",
    "Damson",
    "Date",
    "Dragonfruit",
    "Durian",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Finger Lime",
    "Goji berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Grewia asiatica",
    "Guava",
    "Hala Fruit",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Juniper berry",
    "Kaffir Lime",
    "Kiwano",
    "Kiwifruit",
    "Kumquat",
    "Lemon",
    "Lime",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lulo",
    "Lychee",
    "Magellan Barberry",
    "Mamey Apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Marionberry",
    "Melon",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Musk melon",
    "Watermelon",
    "Miracle fruit",
    "Momordica fruit",
    "Monstera deliciosa",
    "Mulberry",
    "Nance",
    "Nectarine",
    "Orange",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Persimmon",
    "Plantain",
    "Plum",
    "Prune",
    "Pineapple",
    "Pineberry",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Purple mangosteen",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Rose apple",
    "Salal berry",
    "Salak",
    "Sapodilla",
    "Sapote",
    "Satsuma",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Surinam cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Ximenia",
    "Yuzu",
  ];

  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(fruits.filter((fruit) => fruit.toLowerCase().includes(query.toLowerCase())));
    }, Math.random() * 1000);
  });
}

function App() {
  return (
    <div className="App">
      <input />
      <div>Show results here</div>
    </div>
  );
}

export default App;
